#!/bin/false

import os
import os.path
import glob


Import('env')

dir_path = Dir('.').abspath

env.driver_sources += sorted(glob.glob(dir_path + "/tls/*.cpp"))

env.driver_sources += sorted(glob.glob(dir_path + "/*.cpp"))
env.driver_headers += sorted(glob.glob(dir_path + "/*.h"))
