#!/bin/false

import os
import os.path
import glob


Import('env')

dir_path = Dir('.').abspath

env.sources += sorted(glob.glob(dir_path + "/*.cpp"))
env.headers += sorted(glob.glob(dir_path + "/*.h"))
